language: csharp
solution: AutoProc.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet test .\\AutoProc.Tests
 - dotnet pack -c Release
 - dotnet nuget push ./AutoProcMiddleware/bin/Release/*.nupkg -k $NUGET_API_KEY -s https://www.nuget.org